### ISSUE TITLE
Lepší UI pro schvalování pojmů

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/termit-ui#10]
Bylo by fajn moci schválit pojem tlačítkem v detailu pojmu a nemuset jít do editace.

Bylo by fajn vidět u rozpracovaného pojmu v jeho detailu nějakou ikonku. A možná i v seznamu pojmů. Tam mohu filtrovat, to ano, ale IMHO to není jediný možný user interface k tomu vidět jaké pojmy jsou rozpracované.

Možná jen můj názor, tak to chce ještě potvrdit příp. dalšími uživateli.

**Comment by psiotwo** [comment]
Term approvals are colliding with Github PR/review IMO

Proposal 1:
- remove TermIt status (draft/approved) from TermIt - reviews/approvals will be managed by GitHub

Proposal 2:
- think about more detailed workflow, e.g.:
1) domain experts will lead their internal discussions and do their internal approval of the glossary used
2) once glossary maintainer (domain expert) approves a term, it can be used in modeling in OntoGrapher. Draft terms cannot be used for modeling in OntoGrapher.
3) Only approved terms and their models are published to the Github for approval by knowledge engineers.

Proposal 2 would require quite some work on the other tools, but might enhance the workflow we are preparing.

**Comment by psiotwo** [comment]
Implemented as prefLabel immutability for confirmed terms.
