### ISSUE TITLE
Cannot select parent with the same prefLabel

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#101]
When selecting a term with same prefLabel as the current term (and coming from a different vocabulary) as its parent (Prostorový objekt in this example), nothing happens, the term does not appear in the list of parents.

![image](https://user-images.githubusercontent.com/1140626/114664280-c58cde80-9cfb-11eb-876a-6815684aac13.png)

**Comment by ledsoft** [comment]
Unable to reproduce. Could you be more specific? Which vocabulary is the would be parent term from? Can there be a conflict of identifiers?

**Comment by psiotwo** [comment]
Unable to reproduce in the new version either.
