### ISSUE TITLE
When parent term is selected, the particular property is not shown to the user.

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#109]
When I select a parent term, I am offered a dialog for selecting broader/subClassOf. When I choose I get back to the term detail, but at this point I cannot see which option I picked. I believe this would be confusing for users.

Tested on dev.

**Comment by ledsoft** [comment]
I don't understand. By "back to the term detail" you mean term detail editing? If so, I thought we agreed today that the logic of property selection will be reworked, including the result visualization.
