### ISSUE TITLE
Application of data.gov.cz style, flags, project publicity

### ISSUE THREAD

**Issue by ledsoft** [opendata-mvcr/termit-ui#15]
The assembly line is approaching the phase where it will be shown to the public. It is necessary to harmonize it visually with the rest of the data.gov.cz

- [x] colors - see data.gov.cz, consider dark mode support
- [x] flag - see data.gov.cz
- [x] project publicity - see data.gov.cz

**Comment by ledsoft** [comment]
Style definition is in https://www.esfcr.cz/documents/21802/797760/Obecn%C3%A1+%C4%8D%C3%A1st+pravidel+pro+%C5%BEadatele+a+p%C5%99%C3%ADjemce+%28verze+3%29/ce136a35-dd8a-4131-b517-36309f2da511, chapter 19

**Comment by psiotwo** [comment]
The text on footer is almost invisible due to its partial transparency. Maybe it would be enough to just make the background less transparent.

The flag near the middle of the footer seems strange. Having it a bit aside would be better IMO (e.g. in the right corner, similar to mission control).
