### ISSUE TITLE
Action failed after login when coming from mission control

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit-ui#18]
When I get to Termit and I am not logged in, after login, I get:
```Failed to load resource: the server responded with a status of 401 () /termit-server-kodi/rest/vocabularies:1 ```
![image](https://user-images.githubusercontent.com/718827/92725863-0c34e780-f36d-11ea-8a7b-b09e0d50a868.png)

**Comment by ledsoft** [comment]
Fixed in upstream and merged in https://github.com/opendata-mvcr/termit-ui/pull/20, feel free to reopen if the issue resurfaces.
