### ISSUE TITLE
Disable the possibility to CUD vocabularies

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#22]
Vocabularies are added to a workspace through [Control panel](https://github.com/opendata-mvcr/mission-control).

Follow-up of https://github.com/opendata-mvcr/termit-ui/issues/3.

**Comment by ledsoft** [comment]
@psiotwo What about vocabulary editing? I suppose that is the same issue, isn't it.

**Comment by psiotwo** [comment]
Indeed, updated the ticket accordingly.

**Comment by psiotwo** [comment]
Checked. OK.
