### ISSUE TITLE
Unable to create a new vocabulary in a workspace

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/termit-ui#3]
I need to create a new vocabulary in my namespace. Termit provides a button to create a vocabulary. When I click the button, I can see a dialog which I fill in as shown on the picture:

![image](https://user-images.githubusercontent.com/4235208/89045343-aa379a00-d34b-11ea-970f-0f7242a43a67.png)

When I click "Vytvořit", I get this error message and no new vocabulary is created.

![image](https://user-images.githubusercontent.com/4235208/89045335-a441b900-d34b-11ea-885f-1a1ad5489529.png)

So now I do not know how to create a new vocabulary.

**Comment by ledsoft** [comment]
Yes, this is a known issue. The problem is we haven't yet decided whether TermIt should be able to create (and edit) vocabularies or whether that should be responsibility of the Control panel. Therefore, the vocabulary editing is in a sort of a vacuum...

**Comment by martinnec** [comment]
Control panel is a better option IMO.

**Comment by ledsoft** [comment]
Not a bug, keeping it open just for reference.

**Comment by ledsoft** [comment]
Superseded by #22
