### ISSUE TITLE
Redesign List of Vocabularies

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#35]
The goal is to:
1) improve UX of the vocabulary list by using a more user-friendly and intuitive component
2) make the list ready for adding additional information (vocabulary metadata, score, etc.)

**Comment by ledsoft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TermIt: Redesign výběru slovníku](https://trello.com/c/iCdPvLWm/259-termit-redesign-v%C3%BDb%C4%9Bru-slovn%C3%ADku)
