### ISSUE TITLE
URL not preserved after login.

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#4]
Opening TermIt with this URL https://kbss.felk.cvut.cz/termit-kodi/#vocabularies?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance2075382462

gets me to the log-in screen. This is correct. Upon successful login, I expect to be redirected to this URL (/vocabularies with the given workspace to be opened). Instead, I land on dashboard.

**Comment by ledsoft** [comment]
Fixed in upstream (https://github.com/kbss-cvut/termit-ui/pull/9) and merged.
