### ISSUE TITLE
The order of term detail fields is counterintuitive

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#40]
Reorder the fields as follows:
- Label
- Definition
- Source

- Type
- Parent term

- Synonyms
- Search strings
- Comment
- Status

**Comment by blcham** [comment]
If I assume that we will have the same order for each screen (view-term vs. edit-term-in-vocabulary vs. edit-term-in-annotator), which basically means to me that the "view-term" scenario is the most important and dictates mostly the order. The order is reasonable, the only thing that really bothers me is the status at the end (we discussed moving it somewhere to the beginning). 

Notes:
- Definition, Source -- makes sense to have it together
- Type, Parent term -- makes sense to choose Type first -- (it could even mark those "Parent terms" that are not compatible)
- Synonyms, Search strings -- makes sense to have together, although see my note before

**Comment by MichalMed** [comment]
This corresponds a little with the Definition-Source-Link to place in a document ticket in redmine. 
I suggest to put properties to the functional blocks and move them together.
