### ISSUE TITLE
Opening workspace does not work without refresh

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#5]
1) Log-in to control panel at https://mission-control.netlify.app/
1) Log-in to TermIt at https://kbss.felk.cvut.cz/termit-kodi (to prevent #4)
2) Go back to Control panel and open a workspace in TermIt (I used "Registr práv a povinnosti - rozšíření 2020", https://mission-control.netlify.app/workspaces/instance298146956)
3) TermIt opens on the /vocabularies page, but does not list any vocabularies, although the workspace contains three vocs.
4) Upon refresh the list of vocabularies is populated correctly.

**Comment by psiotwo** [comment]
I am still experiencing this issue.

**Comment by ledsoft** [comment]
The fix hasn't been merged, yet.
