### ISSUE TITLE
Event shouldn't be under Endurant

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit-ui#54]
If I understand the "koncepce" correctly, Event is not Endurant. However, it is in the tree structure under Endurant in Termit:
![image](https://user-images.githubusercontent.com/718827/100764970-41deef00-33f7-11eb-846b-274ead454096.png)
![image](https://user-images.githubusercontent.com/718827/100765282-9f733b80-33f7-11eb-8e22-d966f72dd61f.png)

**Comment by psiotwo** [comment]
Fixed in https://github.com/opendata-mvcr/termit-ui/commit/654debfbb723c9b8829d91f090badc65be50830a
