### ISSUE TITLE
Validation not working correctly?

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit-ui#57]
In [this vocabulary](https://kbss.felk.cvut.cz/termit-kodi/#/vocabularies/2013?namespace=https://slovník.gov.cz/legislativní/sbírka/304/) I have "Zapsaná osoba" as object type.
Validation says:
![image](https://user-images.githubusercontent.com/718827/100766864-6a67e880-33f9-11eb-82b7-77f173982ef8.png)

Is the "ontological type" "object type" as can be seen here?
![image](https://user-images.githubusercontent.com/718827/100767084-a3a05880-33f9-11eb-9a68-bffcc30c5912.png)

If so, validation is wrong. If not, it is something I cannot fix in TermIt?

**Comment by psiotwo** [comment]
Yes, this is something You cannot fix through TermIt at present. We should filter out such problems from here

**Comment by psiotwo** [comment]
Fixed in upstream. Should get here upon merge from https://github.com/kbss-cvut/termit-ui .

**Comment by psiotwo** [comment]
@jakubklimek should be fixed.

**Comment by jakubklimek** [comment]
It is
