### ISSUE TITLE
Empty history for vocabularies

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit-ui#58]
I created a vocabulary in mission control and added 4 terms into it. Yet, the vocabulary history is empty:
![image](https://user-images.githubusercontent.com/718827/100767471-18739280-33fa-11eb-8741-7be3b7aaa3be.png)

If this is correct and by design, it is a bit misleading.

**Comment by ledsoft** [comment]
Vocabulary history tracks only changes to vocabulary metadata, so term addition/removal is not recorded. Will remove the history tab, as it conveys no useful information (vocabulary cannot be edited in TermIt anyway).
