### ISSUE TITLE
Home and End keys not working in Term search field

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/termit-ui#63]
When searching for terms, I am unable to use Home and End keys in the text box.
![image](https://user-images.githubusercontent.com/718827/100982047-e53f1980-3547-11eb-9c94-950e34d48257.png)

**Comment by ledsoft** [comment]
The home/end and up/down keys are mapped for navigation in the result list. Only left/right keys work in the input. Would it make sense to override this mapping in case there are no results? Or what would be the most natural behavior, in your opinion?

**Comment by jakubklimek** [comment]
I usually use Home/End to get to the beginning and the end of the text in the input box.
