### ISSUE TITLE
Cannot edit term

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/termit-ui#7]
1) I opened the workspace https://kbss.felk.cvut.cz/termit-kodi/#/vocabularies?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1107673637
2) I edited the term "Křestní jméno" and changed its preferred label to "Jméno fyzické osoby". this succeeded
3) Then I tried to edit the definition (delete it) and upon save I got the following screen.

![Screenshot from 2020-08-07 11-07-20](https://user-images.githubusercontent.com/1140626/89629632-6b9b6580-d89e-11ea-8612-12df5109239a.png)

**Comment by ledsoft** [comment]
Likely caused by https://github.com/kbss-cvut/jopa/issues/73, so it may take some time to fix.

**Comment by ledsoft** [comment]
Backend issue, tracked under https://github.com/opendata-mvcr/termit/issues/25.
