### ISSUE TITLE
nemožnost upravit existující pojem

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/termit-ui#72]
při úpravě existujícího pojmu v TermIt mi nejde kliknout na uložit

**Comment by RadkaDomanska** [comment]
V generickém slovníku datových fondů VS mi nejde opětovně založit pojem "údaj", který jsem v minulosti založila a smazala. Píše mi to chybu Term with identifier https://slovník.gov.cz/generický/datové-fondy/pojem/údaj already exists, ale mezi pojmy ho nevidím.

**Comment by ledsoft** [comment]
Zdravím,
co se týče prvního komentáře, potřeboval bych trochu víc informací. Např., je tlačítko zašedlé (disabled), nebo je aktivní, ale při kliknutí se nic nestane? O který pojem se jedná (nebo se to týká všech)? Je-li zašedlé, jsou dvě možnosti:
1. Chybí nějaký požadovaný parametr pojmu (např. název)
2. Pojem je ve stavu schválený, takové pojmy nelze editovat. V současné verzi TermIta už u schválených pojmů nelze editaci ani otevřít (aby to nemátlo uživatele).

Co se týče druhého komentáře: pojem "údaj" s výše uvedenou IRI v Generickém slovníku datových fondů VS vidím (v pracovním prostoru Datové fondy VS). Opět bych tedy poprosil o upřesnění.

**Comment by RadkaDomanska** [comment]
Dobrý den, upravovat pojmy už mi lze. Myslela jsem, že jste v průběhu mého testování něco opravili. Původně mi nešlo kliknout na tlačítko uložit a problém byl u všech pojmů (myslím, že bylo zašedlé). Vše jsem dělala stejně a jen u mnou vložených stále rozpracovaných pojmů, takže to nemohlo být způsobeno důvodem 1 ani 2. Co se týče pojmu údaj, tak mi to pak také začalo fungovat, takže teď nemám co upřesňovat. Můžete si mé komentáře odškrtnout jako hotové.

**Comment by ledsoft** [comment]
Ok, díky. Zavírám.
