### ISSUE TITLE
Link to assembly line issue tracking in UI

### ISSUE THREAD

**Issue by ledsoft** [opendata-mvcr/termit-ui#82]
As a user, I want to be able to quickly create bug reports and feature requests from TermIt. Since all assembly line tools have source on GitHub, it has been decided to use GitHub issue tracking for this. TermIt UI should contain links to bug report and feature request templates on GitHub.

**Comment by psiotwo** [comment]
Just noticed the button 'Request a feature' has incorrect styling - color and position

![image](https://user-images.githubusercontent.com/1140626/107480547-0f7f0a00-6b7d-11eb-9a8a-ccfac026df32.png)

**Comment by ledsoft** [comment]
This is how Bootstrap dropdown buttons are styled. I will attempt to fix the styling.
