### ISSUE TITLE
IRI nového pojmu generováno bez diakritiky

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/termit-ui#9]
IRI nového pojmu je generováno z názvu, který ručně vyplním. Termit ale z toho vyhazuje diakritiku. Chci to s diakritikou a tak to musím zbytečně přepisovat.

![image](https://user-images.githubusercontent.com/4235208/90230388-c5111080-de19-11ea-97ee-a1c0fe6cdb41.png)

**Comment by psiotwo** [comment]
Seems resolved - closing this issue.
